import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme_provider";
import Menu from "@/components/parts/menu";
import Footer from "@/components/parts/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Menu/>
          {children}
          <div className="p-10"></div>
          <Footer/>
          </ThemeProvider>
      </body>
    </html>
  );
}
